// import { authHeaders } from '../couchdb/helpers'
// import maybeSetupUser from './setup'
// TODO: migrate to custom domain! (wildcard domain supported via route chaning from *.a.test.de to domain worker eg. a.test.de)
import { getEnv } from '/_env.js'
import doReq from '../lib/req.js'
// eslint-disable-next-line no-restricted-imports
import { escapeId } from '../../app/src/lib/helpers.js'
import { decode } from '../lib/jwt.js'

// TODO: CSRF protection for lofi app?
// TODO: auth_domain instead of hard coded
const {
  _setup,
  _couchKey,
  _couchSecret,
  couchHost,
  env,
  folderHash,
  appName,
  workerd
} = getEnv([
  '_setup',
  '_couchKey',
  '_couchSecret',
  'couchHost',
  'env',
  'folderHash',
  'appName',
  'workerd'
])

const authHeaders = { 'Authorization': `Basic ${btoa(_couchKey + ':' + _couchSecret)}` }

// NOTE: deno / workerd local dev setup is a fake test login with zero validation!
// @ts-ignore
const local = (typeof self !== 'undefined' && !!self.Deno) || typeof workerd !== 'undefined'

// function setCookie (name, value, days) {
//     let d = new Date
//     d.setTime(d.getTime() + 24 * 60 * 60 * 1000 * days)
//     document.cookie = name + "=" + value + ";path=/; Expires=" + d.toGMTString()
// }
// function deleteCookie (name) { setCookie(name, '', -1) }

// TODO: better logout detection:
// In order to receive a 401 for an expired session, add the following header to all AJAX requests:
// X-Requested-With: XMLHttpRequest

function getCookie (name, cookieString = '') {
  const v = cookieString.match('(^|;) ?' + name + '=([^;]*)(;|$)')
  return v ? v[2] : null
}


// TODO: move cookie back to /_api/ ? 
// TODO: create database if not existing

export default async function ({ req, stats, app }) {
  let jwtPayload = {}
  let jwt
  if (local && !req.headers['cf-access-jwt-assertion']) {
    // no validation for fake null login only in dev mode
    jwt = getCookie('CF_Authorization', req.headers['cookie'])
    if (jwt) {
      jwtPayload = JSON.parse(atob(jwt.split('.')[1]))
    }
  } else {
    jwt = req.headers['cf-access-jwt-assertion']
    const { valid, payload } = await decode(jwt)
    if (!valid) {
      return new Response('forbidden: token', { status: 403 })
    }

    jwtPayload = payload

    // TODO:what is the org flow? for github etc?
    // ${jwtPayload.iss}
    // const identity = await doReq(`https://lanespm.cloudflareaccess.com/cdn-cgi/access/get-identity`, {
    //     headers: { cookie: `CF_Authorization=${jwt}` }
    //   })
    // github:  {
    //   "id": 1176068,
    //   "name": "Jan Johannes",
    //   "email": "jan@ntr.io",
    //   "idp": {
    //     "id": "55f83bb2-0d88-4a4d-852f-85b777d13e92",
    //     "type": "github"
    //   },
    //   "geo": {
    //     "country": "EE"
    //   },
    //   "user_uuid": "5bfedae6-c211-57ea-81e4-d143787e5b5b",
    //   "account_id": "302c98e0d4fb9f5157a57ea35aa8ff82",
    //   "iat": 1740165842,
    //   "ip": "85.253.100.191",
    //   "service_token_status": false,
    //   "orgs": [
    //     {
    //       "id": 3406112,
    //       "name": "pouchdb"
    //     },
    //     {
    //       "id": 6655347,
    //       "name": "neutrinity"
    //     },
    //     {
    //       "id": 39856753,
    //       "name": "cloudless-hq"
    //     }
    //   ],
    //   "teams": [
    //     {
    //       "name": "Maintainers",
    //       "org_id": 3406112
    //     },
    //     {
    //       "name": "botbox",
    //       "org_id": 6655347
    //     }
    //   ]
    // }
    // idp	Data from your identity provider.
    // geo	The country where the user authenticated from.
    // user_uuid	The ID of the user.
    // devicePosture	The device posture attributes.
    // account_id	The account ID for your organization.
    // iat	The timestamp indicating when the user logged in.
    // ip	The IP address of the user.
    // service_token_status	True if authentication was through a service token instead of an IdP.
    // is_gateway	True if the user enabled WARP and authenticated to a Zero Trust team.
    // gateway_account_id	An ID generated by the WARP client when authenticated to a Zero Trust team.
    // device_id	The ID of the device used for authentication.
    // device_sessions	A list of all sessions initiated by the user.
  }

  let cont = null

  if (req.query.continue && req.query.continue !== '/' && req.query.continue !== 'null' && req.query.continue !== 'undefined') {
    cont = req.query.continue
}

  if (cont && (!cont.startsWith('/') || cont.includes('..') || cont.includes('http'))) {
    return new Response('forbidden: continue', { status: 403 })
  }
  
  if (req.url.search.startsWith('?logout')) { // req.method === 'delete' for deletion session doc?
    const headers = { 'Cache-Control': 'must-revalidate' };

    let continueParam = ''
    if (cont) {
      continueParam = '?continue=' + encodeURIComponent(cont)
    }

    if (jwtPayload.dev_mock) {
      headers['Location'] = `/_ayu/accounts/${continueParam}`
      headers['Set-Cookie'] = 'CF_Authorization=deleted; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT; SameSite=Strict; HttpOnly'
    } else if (jwtPayload.email) {
      const base = `/` // _ayu/accounts/${continueParam}`
      headers['Location'] = `/cdn-cgi/access/logout?returnTo=${encodeURIComponent(req.url.origin + base)}`
      headers['Set-Cookie'] = 'CF_Authorization=deleted; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Secure; SameSite=Strict; HttpOnly'
      headers['Set-Cookie'] = 'AYU_SESSION_ID=deleted; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Secure; SameSite=Strict; HttpOnly'
    } else {
      headers['Location'] = `/` // _ayu/accounts/?login
      headers['Set-Cookie'] = 'CF_Authorization=deleted; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT; SameSite=Strict; Secure; HttpOnly'
    }

    return new Response('', {
      status: 302,
      headers
    })
  }

  // FIXME: ?
  // if (req.url.pathname === ('/_session') && req.method === 'DELETE') {
  //   return new Response('redirect', {
  //     status: 303,
  //     headers: { 'Location': 'https://' + req.url.hostname + '/cdn-cgi/access/logout' }
  //   })
  // }

  let curSessionId
  if (local) {
    curSessionId = jwtPayload.sessionId
  } else {
    // FIXME: remove ayu session id?
    const sessionId = getCookie('AYU_SESSION_ID', req.headers['cookie'])
    // const sessionIdParts = (sessionId && sessionId.split('__')) || []
    curSessionId = sessionId // sessionIdParts[0]
    // curOrg = sessionIdParts[1]
  }

  const userAgent = req.headers['user-agent']
  let browserName
  if (userAgent.includes('Edg')) {
    browserName = 'Edge'
  } else if (userAgent.includes('Chrome')) {
    browserName = 'Chrome'
  } else if (userAgent.includes('Safari')) {
    browserName = 'Safari'
  } else if (userAgent.includes('Firefox')) {
    browserName = 'Firefox'
  }

  const cf = { ...req.raw.cf, tlsClientAuth: undefined, tlsExportedAuthenticator: undefined, tlsCipher: undefined, clientTcpRtt: undefined, edgeRequestKeepAliveStatus: undefined, requestPriority: undefined, clientAcceptEncoding: undefined, tlsVersion: undefined, httpProtocol: undefined }

  const email = jwtPayload.email || local && req.query.email
  const appDbName = 'ayu_app_' + (env === 'prod' ? escapeId(appName) : escapeId(env + '__' + appName))
  const userDbName = email && 'ayu_user_' + (env === 'prod' ? escapeId(email) : escapeId(env + '__' + email))
  const userSettingsId = email && 'lanes:settings_' + escapeId(email)

  // TODO:
  const inviteProjectId = req.query.inviteProjectId
  const inviteOrgId = req.query.inviteOrgId

  if (req.url.search.startsWith('?login')) {
    if (!jwtPayload.email && !req.query?.email) {
      return new Response('forbidden: no email identity', { status: 403 })
    }

    const orgName = req.query.org
    const startDemoProject = req.query.startDemoProject
    const projectName = req.query.projectName

    if (startDemoProject && !cont) {
      cont = '/projects/00000'
    }

    // TODO: if already logged in, logout or error?

    const newSession = {
      email: local ? req.query.email : jwtPayload.email,
      useSessionId: local ? req.query.sessionId : curSessionId,
      userDbName,
      userSettingsId,
      sessionName: req.query.sessionName,
      app,
      cf,
      browserName
    }

    let newSessionId
    if (couchHost) {
      newSessionId = await ensureSession(newSession, { appDbName, setupOptions: { orgName, projectName, inviteProjectId, inviteOrgId } })
    } else {
      newSessionId = 'ephemeral:' + crypto.randomUUID()
    }

    if (local) {
      // NOTE: deno local is a fake test login with zero validation!
      const devJwt = 'dev.' + btoa(JSON.stringify({
        dev_mock: true,
        email: newSession.email,
        sessionId: newSessionId
      }))

      return new Response(null, {
        status: 302,
        headers: {
          'Cache-Control': 'must-revalidate',
          'Location': cont || '/' ,
          'Set-Cookie': `CF_Authorization=${devJwt}; Path=/; Expires=Tue, 19 Jan 2038 04:14:07 GMT; SameSite=Strict; HttpOnly`
        }
      })
    }

    // is logged in after redirect back from cf access, just need to set session id cookie and redirect back
    return new Response(null, {
      status: 302,
      headers: {
        'Cache-Control': 'must-revalidate',
        // ${newSession.org ? '__' + newSession.org : ''}
        'Set-Cookie': `AYU_SESSION_ID=${newSessionId}; Path=/; HttpOnly; SameSite=Strict; Secure; Expires=Tue, 19 Jan 2038 04:14:07 GMT`,
        'Location': cont || '/'
      }
    })
  }

  // const sessions = await req(`${`${dbHost}/user_${userId}`}/_design/ntr/_view/lastSeen_by_userId?reduce=false`)

  return new Response(JSON.stringify({
    userId: jwtPayload.email,
    email: jwtPayload.email,

    env,
    appName: app.appName,
    appHash: folderHash,

    userDbName,
    userSettingsId,

    sessionId: curSessionId,

    // roles: [],
    cf,
    browserName,

    expiry: jwtPayload.exp,
    issued: jwtPayload.iat,

    cfAccessUserId: jwtPayload.sub
  }), {
    status: 200,
    headers: { 'Content-Type': 'application/json' }
  })
}

async function ensureSession ({
  userSettingsId,
  useSessionId,
  email,
  sessionName,
  app,
  cf,
  browserName,
  userDbName 
}, {
  appDbName,
  setupOptions: { orgName, projectName, inviteProjectId, inviteOrgId }
}) {
  let newSessionDoc

  if (useSessionId) {
    const sessionDocRes = await doReq(`${couchHost}/${userDbName}/${useSessionId}`, {
      headers: authHeaders
    })

    console.warn('validate session doc', sessionDocRes)

    const { json: existingSessionDoc } = sessionDocRes
    if (existingSessionDoc) {
      // TODO: error if any value changed or doc is unavailable, validation
      newSessionDoc = existingSessionDoc
    }
  }
  
  // TODO: setup user/org association
  const orgDbs = []
  if (!newSessionDoc?._id) {
    let { json: { error, update_seq: userDbUpdateSeq } } = await doReq(`${couchHost}/${userDbName}`, { headers: authHeaders })
      
    // Create new user with session
    if (error === 'not_found') {
      // generate integer user id
      const lanesUserId = Date.now() + Math.floor(Math.random() * 10000)

      // users db is currently only used to enforcy unique usernames
      const userRes = await doReq(`${couchHost}` + '/_users', {
        method: 'POST',
        body: {
          _id: 'org.couchdb.user:' + lanesUserId,
          name: `${lanesUserId}`,
          userDbName,
          created_at: Date.now(),
          updated_at: Date.now(),
          userSettingsId,
          roles: [],
          type: "user"
        },
        headers: authHeaders
      })

      // just crash and let user try again
      if (!userRes?.json?.ok) {
        throw new Error('errror reserving user id')
      }

      await doReq(`${couchHost}/${userDbName}`, {
        method: 'PUT',
        headers: authHeaders
      })
  
      await doReq(`${couchHost}/${userDbName}` + '/_security', {
        method: 'PUT',
        body: {
          admins: {
            names: [],
            roles: ["_admin"]
          },
          members: {
            names: [lanesUserId],
            roles: []
          }
        },
        headers: authHeaders
      })

      // org, projectName
      let lanesOrgId
      let orgDbName
      if (orgName) {
        lanesOrgId = Date.now() + Math.floor(Math.random() * 10000)
        orgDbName = 'org_' + lanesOrgId

        await doReq(`${couchHost}/${orgDbName}`, {
          method: 'PUT',
          headers: authHeaders
        })
    
        await doReq(`${couchHost}/${orgDbName}` + '/_security', {
          method: 'PUT',
          body: {
            admins: {
              names: [],
              roles: ["_admin"]
            },
            members: {
              names: [lanesUserId],
              roles: []
            }
          },
          headers: authHeaders
        })

        orgDbs.push({
          dbName: orgDbName,
          startSeq: null,
          push: null,
          pull: null
        })
      }

      // TODO use couch username conversion Buffer.from(prefixedHexName.replace('userdb-', ''), 'hex').toString('utf8')
      // 'userdb-' + Buffer.from(name).toString('hex');
      const username = email.split('@')[0]

      // split username by any non-word character
      const wordParts = username.split(/\W+/)
      let initials
      if (wordParts.length > 1) {
        initials = (wordParts[0].slice(0, 1) + wordParts[1].slice(0, 1)).toUpperCase()
      } else {
        initials = username.slice(0, 2).toUpperCase()
      }

      await doReq(`${couchHost}/${userDbName}` + '/_bulk_docs', {
        method: 'POST',
        body: {
          docs: [
            // FIXME: move to _setup call
            {
                _id: userSettingsId,
                lanesUserId, // FIXME username is global unique per user
                username,
                name: username, // TODO: ask later? or ask at onboarding! + make unique on org level?
                initials,
                created_at: Date.now(),
                updated_at: Date.now(),
                time_zone: {
                  olson_name: "Europe/Helsinki", // TODO: send with onboarding name form data from client!
                  offset: "+02:00"
                }
            }
          ]
        },
        headers: authHeaders
      })

      console.log(await doReq(`${couchHost}/_replicate`, {
        method: 'POST',
        body: {"source": appDbName, "target": userDbName },
        headers: authHeaders
      }))

      console.log(orgDbName && await doReq(`${couchHost}/_replicate`, {
        method: 'POST',
        body: {"source": appDbName, "target": orgDbName },
        headers: authHeaders
      }))

      // FIXME: setup replication from app db
      
      const retryRes = await doReq(`${couchHost}/${userDbName}`, { headers: authHeaders })
      userDbUpdateSeq = retryRes.json.update_seq

      if (_setup?.fetch) {
        await _setup.fetch('http://local/_api/_setup', {
          method: 'POST',
          // FIXME: make generic arg handover possible and move lanes specifics t _setup
          body: JSON.stringify({ orgId: lanesOrgId, orgName, projectName, inviteProjectId, inviteOrgId, email }),
          headers: {
            'content-type': 'application/json',
            'ayu-token': 'FIXME: asdffasdf asdfasd ' // internal rpc call or internal namespace in routing or internal secret
          }
        })
      }
    }

    newSessionDoc = {
      _id: 'session:' + crypto.randomUUID(),
      sessionName: sessionName,
      email: email,
      created: Date.now(),
      cf,
      browserName,
      app,
      loginCount: 0,
      type: 'session',
      dbs: [
        {
          dbName: userDbName,
          startSeq: userDbUpdateSeq,
          push: null,
          pull: null
        },
        ...orgDbs
      ]
      // user-agent, saveToDevice
    }
  }

  newSessionDoc.lastLogin = Date.now()
  newSessionDoc.loginCount++

  await doReq(`${couchHost}/${userDbName}/${newSessionDoc._id}`, {
    method: 'PUT',
    body: newSessionDoc,
    headers: {
      'Authorization': `Basic ${btoa(_couchKey + ':' + _couchSecret)}`
    }
  })

  return newSessionDoc._id
}
