export default [
  '**/.git/**',
  '.git/**',
  '**/**.build.css',
  'node_modules/**',
  '**/node_modules/**',
  'yarn.lock',
  '**/*.svelte.js',
  '**/build/**',
  '**/*.svelte.ssr.js',
  '.gitignore',
  '**/.devcontainer/**',
  'README.md',
  '**/*.svelte.css',
  '**/.github/**',
  '**/*.map',
  '**/ipfs-map.json',
  '**/*.bundle.js'
]
