import versions from './versions.json' assert { type: 'json' }
const { ayuVersion } = versions

const denoHome = Deno.env.get('DENO_HOME') || Deno.env.get('HOME') + '/.deno'

const permissions = [
  '--allow-read=./,\`command -v deno\`,$DENO_DIR/',
  '--allow-env=HOME,DENO_DIR,DENO_HOME,ESBUILD_BINARY_PATH,DENO_AUTH_TOKENS',
  '--allow-hrtime',
  '--allow-net=atreyu.dev,127.0.0.1:5001,127.0.0.1:8080,localhost,api.cloudflare.com,api.pinata.cloud,registry.npmjs.org,deno.land,c3b0b243-4f69-4cb1-9ece-1b0561a67cee-bluemix.cloudant.com',
  '--allow-run=kill,yarn,ipfs,\`command -v deno\`,"$ESBUILD_BINARY_PATH","$HOME"/Library/Caches/esbuild/bin/esbuild-darwin-arm64@0.14.51',
  '--allow-write="$TMPDIR","$DENO_DIR"/,"$HOME"/.atreyu,./',
  '--no-check',
  '--unstable'
]
// FIXME: ayu update installs new cli with old script and old permissions!
export function install (newAyuVersion) {
  const runCommand = `#!/bin/sh
# generated by ayu

exec deno run ${permissions.join(' \\\n')} 'https://atreyu.dev/ayu@${newAyuVersion}/cli/mod.js' "$@"
`
  Deno.writeTextFileSync(denoHome + '/bin/ayu', runCommand, { mode: 0o755 })
  // TODO: execute and fetch dependencies

  console.log(`\nInstalled ayu script https://atreyu.dev/ayu@${newAyuVersion}/cli/mod.js with following permissions:\n` + permissions.join(' \n'))
}

if (import.meta.main) {
  console.log('installing ayu cli ' + ayuVersion + ' ...')
  install(ayuVersion)
}
