# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Container

on:
  push:
    branches:
      - "master"
    paths:
      - Dockerfile
      - .github/workflows/container.yml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  AYU_VERSION: 0.5.6

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          # context: ./ # .devcontainer
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.AYU_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: AYU_VERSION=${{ env.AYU_VERSION }}
